# Source: f5-bigip-ctlr/templates/f5-bigip-ctlr-deploy.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bigip1-f5-bigip-ctlr
  labels:
    app: f5-bigip-ctlr
    chart: f5-bigip-ctlr-0.0.6
    release: bigip1
    heritage: Tiller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: f5-bigip-ctlr
        release: bigip1
    spec:
      serviceAccountName: bigip1-f5-bigip-ctlr
      imagePullSecrets:
        - name: f5-docker-images
        - name: bigip-login
      containers:
      - name: f5-bigip-ctlr
        image: "f5networks/k8s-bigip-ctlr:1.9.0"
        volumeMounts:
        - name: bigip-creds
          mountPath: "/tmp/creds"
          readOnly: true
        imagePullPolicy: IfNotPresent
        command:
        - /app/bin/k8s-bigip-ctlr
        args:
        - --credentials-directory
        - /tmp/creds
        - --bigip-partition
        - "kubernetes"
        - --bigip-url
        - "10.1.20.10"
        - --flannel-name
        - "flannel_vxlan"
        - --insecure
        - "true"
        - --pool-member-type
        - "cluster"
      volumes:
      - name: bigip-creds
        secret:
           secretName: bigip-login

