apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-bigip2-ctlr-deployment
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      name: k8s-bigip2-ctlr
      labels:
        app: k8s-bigip2-ctlr
    spec:
      serviceAccountName: bigip-ctlr
      containers:
        - name: k8s-bigip2-ctlr
          # replace the version as needed
          image: "f5networks/k8s-bigip-ctlr:1.4.1"
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bigip-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bigip-login
                  key: password
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--bigip-url=10.1.10.61",
            "--bigip-partition=kubernetes",
            # The Controller can use local DNS to resolve hostnames;
            # defaults to LOOKUP; can be replaced with custom DNS server IP
            # or left blank (introduced in v1.3.0)
            "--resolve-ingress-names=LOOKUP",
            "--pool-member-type=cluster",
            "--flannel-name=flannel_vxlan"
            # The Controller can access Secrets by default;
            # set to "false" if you only want to use preconfigured
            # BIG-IP SSL profiles
            #"--use-secrets=false",
            # The Controller watches all namespaces by default.
            # To manage a single namespace, or multiple namespaces, provide a
            # single entry for each. For example:
            # "--namespace=test",
            # "--namespace=prod"
            ]
      imagePullSecrets:
        - name: f5-docker-images
        - name: bigip-login
