apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: f5-ingress
  annotations:
    custom_ip: "10.1.10.80"
spec:
  rules:
  - host: www.f5demo.com
    http:
      paths:
      - backend:
          serviceName: my-website
          servicePort: 80
  - host: app1.f5demo.com
    http:
      paths:
      - backend:
          serviceName: app1
          servicePort: 80
