---
# Source: F5Demo/templates/configmap.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: f5demo-as3-configmap
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.1.0",
        "id": "f5demo",
        "label": "CIS AS3 Example",
        "remark": "Example of using CIS",
        "AS3": {
          "class": "Tenant"
       },
       "Common": {
          "class": "Tenant"
       }
    }
    }

