kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-as3-configmap
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.1.0",
        "id": "{{ .Release.Name }}",
        "label": "CIS AS3 Example",
        "remark": "Example of using CIS",{{- if not .Values.f5demo.delete }}
        "Common": {
                "class": "Tenant",
                "Shared": {
                        "class": "Application",
                        "template": "shared"{{- if .Values.f5demo.dns }},
                        "AS3Server": {
                                "class": "GSLB_Server",
                                "dataCenter": 
                                         {"bigip":"/Common/UDF"}
                                ,
                                "devices": [{
                                                "address": "10.1.10.240",
                                                "addressTranslation": "10.1.10.240"
                                        }
                                ]
                                ,
                                "virtualServers": [{
                                                "address": "10.1.10.81",
                                                "port": 80,
                                                "addressTranslation": "10.1.10.81",
                                                "addressTranslationPort":80
                                        },
                                        {
                                                "address": "10.1.10.82",
                                                "port": 80,
                                                "addressTranslation": "10.1.10.82",
                                                "addressTranslationPort":80
                                        },
                                        {
                                                "address": "10.1.10.240",
                                                "port": 6443,
                                                "addressTranslation": "10.1.10.240",
                                                "addressTranslationPort":6443
                                        }
                                ]
                        }{{- end }}

                }
        },{{- end }}
        "AS3": {
          "class": "Tenant"{{- if not .Values.f5demo.delete }},
          "Shared": {
            "class": "Application",
            "template":"shared",
            "serviceAddress0": {
              "class": "Service_Address",
              "virtualAddress": "10.1.10.81"
            }, "web_pool": {
              "class": "Pool",
              "monitors": [
                "http"
              ],
              "members": [
                {
                  "servicePort": 80,
                  "serverAddresses": []
                }
              ]
            }
          },
          "A1": {
            "class": "Application",
            "template": "{{- if .Values.f5demo.http }}http{{- else }}tcp{{- end }}",
            "serviceMain": {
              "class": "Service_{{- if .Values.f5demo.http }}HTTP{{- else }}TCP{{- end }}",
              "virtualAddresses": [
                {"use": "/AS3/Shared/serviceAddress0"}
              ],{{- if not .Values.f5demo.http }}
              "virtualPort": 80,{{- end }}
              "pool": "/@/Shared/web_pool"
            },
            "web_pool": {
              "class": "Pool",
              "monitors": [
                "http"
              ],
              "members": [
                {
                  "servicePort": 80,
                  "serverAddresses": []
                }
              ]
            }
          },
          "A2": {
            "class": "Application",
            "template": "{{- if .Values.f5demo.http }}https{{- else }}tcp{{- end }}",
            "serviceMain": {
              "class": "Service_{{- if .Values.f5demo.http }}HTTPS{{- else }}TCP{{- end }}",
              "virtualAddresses": [
                {"use": "/AS3/Shared/serviceAddress0"}
              ],{{- if not .Values.f5demo.http }}
              "virtualPort": 443,{{- end }}
              "pool": "/@/Shared/web_pool",
              "serverTLS": "webtls",
              "redirect80":false{{- if .Values.f5demo.waf }},
              "policyWAF":{"bigip":"/Common/linux-low"},
              "securityLogProfiles": [
              {
                "bigip": "/Common/Log all requests"
              }
              ]{{- end }}
            },
            "web_pool": {
              "class": "Pool",
              "monitors": [
                "http"
              ],
              "members": [
                {
                  "servicePort": 80,
                  "serverAddresses": []
                }
              ]
            },
            "webtls": {
              "class": "TLS_Server",
              "certificates": [
                {
                  "certificate": "webcert"
                }
              ]
            },
            "webcert": {
              "class": "Certificate",
              "certificate": "-----BEGIN CERTIFICATE-----\nMIICnDCCAgWgAwIBAgIJAJ5n2b0OCEjwMA0GCSqGSIb3DQEBCwUAMGcxCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApXYXNoaW5ndG9uMRAwDgYDVQQHDAdTZWF0dGxlMRQwEgYDVQQKDAtmNV9OZXR3b3JrczEbMBkGA1UEAwwSc2FtcGxlLmV4YW1wbGUubmV0MB4XDTE3MTEyNjE5NTAyNFoXDTE4MDIyNTE5NTAyNFowZzELMAkGA1UEBhMCVVMxEzARBgNVBAgMCldhc2hpbmd0b24xEDAOBgNVBAcMB1NlYXR0bGUxFDASBgNVBAoMC2Y1X05ldHdvcmtzMRswGQYDVQQDDBJzYW1wbGUuZXhhbXBsZS5uZXQwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBALEsuXmSXVQpYjrZPW+WiTBjn491mwZYT7Q92V1HlSBtM6WdWlK1aZN5sovfKtOX7Yrm8xa+e4o/zJ2QYLyyv5O+t2EGN/4qUEjEAPY9mwJdfzRQy6Hyzm84J0QkTuUJ/EjNuPji3D0QJRALUTzu1UqqDCEtiN9OGyXEkh7uvb7BAgMBAAGjUDBOMB0GA1UdDgQWBBSVHPNrGWrjWyZvckQxFYWO59FRFjAfBgNVHSMEGDAWgBSVHPNrGWrjWyZvckQxFYWO59FRFjAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4GBAJeJ9SEckEwPhkXOm+IuqfbUS/RcziifBCTmVyE+Fa/j9pKSYTgiEBNdbJeBEa+gPMlQtbV7Y2dy8TKx/8axVBHiXC5geDML7caxOrAyHYBpnx690xJTh5OIORBBM/a/NvaR+P3CoVebr/NPRh9oRNxnntnqvqD7SW0U3ZPe3tJc\n-----END CERTIFICATE-----",
              "privateKey": "-----BEGIN RSA PRIVATE KEY-----\nProc-Type: 4,ENCRYPTED\nDEK-Info: AES-256-CBC,D8FFCE6B255601587CB54EC29B737D31\n\nkv4Fc3Jn0Ujkj0yRjt+gQQfBLSNF2aRLUENXnlr7Xpzqu0Ahr3jS1bAAnd8IWnsR\nyILqVmKsYF2DoHh0tWiEAQ7/y/fe5DTFhK7N4Wml6kp2yVMkP6KC4ssyYPw27kjK\nDBwBZ5O8Ioej08A5sgsLCmglbmtSPHJUn14pQnMTmLOpEtOsu6S+2ibPgSNpdg0b\nCAJNG/KHe+Vkx59qNDyDeKb7FZOlsX30+y67zUq9GQqJEDuysPJ2BUNP0IJXAjst\nFIt1qNoZew+5KDYs7u/lPxcMGTirUhgI84Jy4WcDvSOsP/tKlxj04TbIE3epmSKy\n+TihHkwY7ngIGtcm3Sfqk5jz2RXoj1/Ac3SW8kVTYaOUogBhn7zAq4Wju6Et4hQG\nRGapsJp1aCeZ/a4RCDTxspcKoMaRa97/URQb0hBRGx3DGUhzpmX9zl7JI2Xa5D3R\nmdBXtjLKYJTdIMdd27prBEKhMUpae2rz5Mw4J907wZeBq/wu+zp8LAnecfTe2nGY\nE32x1U7gSEdYOGqnwxsOexb1jKgCa67Nw9TmcMPV8zmH7R9qdvgxAbAtwBl1F9OS\nfcGaC7epf1AjJLtaX7krWmzgASHl28Ynh9lmGMdv+5QYMZvKG0LOg/n3m8uJ6sKy\nIzzvaJswwn0j5P5+czyoV5CvvdCfKnNb+3jUEN8I0PPwjBGKr4B1ojwhogTM248V\nHR69D6TxFVMfGpyJhCPkbGEGbpEpcffpgKuC/mEtMqyDQXJNaV5HO6HgAJ9F1P6v\n5ehHHTMRvzCCFiwndHdlMXUjqSNjww6me6dr6LiAPbejdzhL2vWx1YqebOcwQx3G\n-----END RSA PRIVATE KEY-----",
              "passphrase": {
                "ciphertext": "ZjVmNQ==",
                "protected": "eyJhbGciOiJkaXIiLCJlbmMiOiJub25lIn0"
              }
            }
          }{{ if .Values.f5demo.dns }},
          "G0": {
            "class": "Application",
            "template": "generic",
            "myfrontendpool": {
                "class": "GSLB_Pool",
                "members": [
                    {
                        "ratio": 10,
                        "server": {
                            "use": "/Common/Shared/AS3Server"
                        },
                        "virtualServer": "0"
                    }
                ],
                "resourceRecordType": "A"
            },
                        "testDomain": {
                                "class": "GSLB_Domain",
                                "domainName": "my-frontend.apps.example.com",
                                "resourceRecordType": "A",
                                "pools": [{
                                                "use": "myfrontendpool"
                                        }
                                ]
                        }
           },
          "G1": {
            "class": "Application",
            "template": "generic",
            "ingresspool": {
                "class": "GSLB_Pool",
                "members": [
                    {
                        "ratio": 10,
                        "server": {
                            "use": "/Common/Shared/AS3Server"
                        },
                        "virtualServer": "1"
                    }
                ],
                "resourceRecordType": "A"
            },
                        "testDomain": {
                                "class": "GSLB_Domain",
                                "domainName": "*.f5demo.com",
                                "resourceRecordType": "A",
                                "pools": [{
                                                "use": "ingresspool"
                                        }
                                ]
                        }
           },
          "G2": {
            "class": "Application",
            "template": "generic",
            "k8sapipool": {
                "class": "GSLB_Pool",
                "members": [
                    {
                        "ratio": 10,
                        "server": {
                            "use": "/Common/Shared/AS3Server"
                        },
                        "virtualServer": "2"
                    }
                ],
                "resourceRecordType": "A"
            },
                        "testDomain": {
                                "class": "GSLB_Domain",
                                "domainName": "k8s.f5demo.com",
                                "resourceRecordType": "A",
                                "pools": [{
                                                "use": "k8sapipool"
                                        }
                                ]
                        }
           }{{ end }}{{- end }}
        }
      }
    }
